# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 08:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home', models.IntegerField(default=0)),
                ('draw', models.IntegerField(default=0)),
                ('away', models.IntegerField(default=0)),
                ('out', models.CharField(max_length=10, null=True)),
                ('result', models.IntegerField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(default='Friendly', max_length=30)),
                ('round', models.CharField(blank=True, default='', max_length=10)),
                ('link', models.CharField(blank=True, default='', max_length=100)),
                ('deadline', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(default='n/a', max_length=5)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Event')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Match')),
            ],
        ),
        migrations.CreateModel(
            name='MatchEventOfTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.MatchEvent')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=10)),
                ('stadium', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('intro', models.CharField(max_length=300)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('playable', models.BooleanField(default=True)),
                ('winners_calculated', models.BooleanField(default=False)),
                ('mode', models.CharField(default='free', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(max_length=5)),
                ('category', models.IntegerField()),
                ('status', models.CharField(default='created', max_length=20)),
                ('result', models.BigIntegerField(default=None, null=True)),
                ('rank', models.IntegerField(default=None, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('payoff', models.FloatField(null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='matcheventofticket',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Ticket'),
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_team', to='game.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='game.Team'),
        ),
        migrations.AddField(
            model_name='bet',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Match'),
        ),
        migrations.AddField(
            model_name='bet',
            name='user_ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.UserTicket'),
        ),
    ]
