# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-27 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='match',
        ),
        migrations.AddField(
            model_name='bet',
            name='match_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='game.MatchEvent'),
        ),
    ]
