# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-03 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_ticket_only_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchevent',
            name='status',
            field=models.CharField(default='Not yet started', max_length=15),
        ),
    ]
