# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-04-09 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_matchevent_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchevent',
            name='status',
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='Not yet started', max_length=15),
        ),
    ]
