# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-07 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='basic_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='monthly_points',
            field=models.IntegerField(default=0),
        ),
    ]
