# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20170207_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='game_money',
            field=models.FloatField(default=1000),
        ),
    ]
